const $=s=>document.querySelector(s);
const video=$('#robotVideo');
let run=null, selected=5, expanded=null, lastDraw=0, raf=0;
const DURATION=16.6667;
const colors={cyan:'#67e0e8',lime:'#c4ec80',amber:'#ffbe75',red:'#ff817e',muted:'#91a8ad'};
const faultNames={bearing:'Ổ bi / truyền động',friction:'Ma sát / bôi trơn',thermal:'Quá nhiệt',backlash:'Sai lệch tư thế',slow:'Chuyển động chậm'};
const el={seek:$('#seek'),time:$('#timeText'),big:$('#timeBig'),frame:$('#frameBig'),play:$('#playBtn')};
function fmt(t){let m=Math.floor(t/60),s=t%60;return `${String(m).padStart(2,'0')}:${s.toFixed(2).padStart(5,'0')}`}
function idx(){return Math.max(0,Math.min(run.timeline.length-1,Math.round((video.currentTime||0)*run.fps)))}
function frame(){return run.timeline[idx()]}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,options={}){const r=await fetch(path,options);const data=await r.json();if(!r.ok)throw new Error(data.detail||'Lỗi API');return data}
async function load(id='default'){run=await api(`/api/run/${id}`);$('#csv').href=`/api/run/${id}/export.csv`;el.seek.max=run.duration_s-1/run.fps;$('#faultLandmark').innerHTML=run.landmarks.map((n,j)=>`<option value="${j}">${escapeHtml(n)}</option>`).join('');$('#faultLandmark').value=selected;renderLandmarks();renderInjections();renderIncidents();tick(true)}
function renderLandmarks(){const row=frame();$('#landmarkGrid').innerHTML=run.landmarks.map((n,j)=>{const p=row.points[j];const short=n.split(' / ')[0];return `<button class="landmark ${selected===j?'active':''}" data-j="${j}"><span class="n">${short}</span><span class="label">${escapeHtml(n.split(' / ')[1]||'')}</span><span class="value">${p?`${Math.round(p[0])}, ${Math.round(p[1])}`:'KHUẤT'}</span></button>`}).join('');document.querySelectorAll('.landmark').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.j);$('#faultLandmark').value=selected;renderLandmarks();tick(true)})}
function updateLandmarks(row){document.querySelectorAll('.landmark').forEach((b,j)=>{const p=row.points[j];b.querySelector('.value').textContent=p?`${Math.round(p[0])}, ${Math.round(p[1])}`:'KHUẤT'})}
function drawOverlay(row){const c=$('#poseOverlay'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);const p=row.points[selected];if(!p)return;const r=10+2*Math.sin(performance.now()/180);x.beginPath();x.arc(p[0],p[1],r,0,Math.PI*2);x.strokeStyle=colors.lime;x.lineWidth=3;x.stroke();x.beginPath();x.arc(p[0],p[1],2,0,Math.PI*2);x.fillStyle=colors.lime;x.fill();x.font='bold 12px Arial';const label=run.landmarks[selected].split(' / ')[0];x.fillStyle='#0b2024de';x.fillRect(p[0]+12,p[1]-27,50,21);x.fillStyle=colors.lime;x.fillText(label,p[0]+20,p[1]-12)}
function setupCanvas(c){const d=window.devicePixelRatio||1;const w=c.clientWidth;const h=Number(c.dataset.logicalHeight||(c.dataset.logicalHeight=c.getAttribute('height')));if(c.width!==Math.round(w*d)||c.height!==Math.round(h*d)){c.width=Math.round(w*d);c.height=Math.round(h*d)}const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);return {x,w,h}}
function lineChart(id,series,opts={}){const c=document.getElementById(id),{x,w,h}=setupCanvas(c);x.clearRect(0,0,w,h);const pad={l:36,r:10,t:13,b:25},W=w-pad.l-pad.r,H=h-pad.t-pad.b;
 const values=series.flatMap(s=>s.values.filter(v=>v!==null&&Number.isFinite(v)));let min=opts.min??Math.min(...values),max=opts.max??Math.max(...values);if(!Number.isFinite(min)){min=0;max=1}if(max<=min)max=min+1;const gap=(max-min)*.12;min=opts.min??Math.max(0,min-gap);max=opts.max??max+gap;
 x.strokeStyle='#30414a';x.lineWidth=1;x.font='10px monospace';x.fillStyle='#8199a0';for(let k=0;k<3;k++){const y=pad.t+H*k/2;x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();x.fillText((max-(max-min)*k/2).toFixed(max>100?0:1),2,y+3)}for(let k=0;k<5;k++){const xx=pad.l+W*k/4;x.beginPath();x.moveTo(xx,pad.t);x.lineTo(xx,pad.t+H);x.stroke();x.fillText((run.duration_s*k/4).toFixed(0)+'s',xx-8,h-5)}
 for(const s of series){x.beginPath();let open=false;s.values.forEach((v,i)=>{if(v===null||!Number.isFinite(v)){open=false;return}const xx=pad.l+W*i/(s.values.length-1),yy=pad.t+H*(max-v)/(max-min);if(!open){x.moveTo(xx,yy);open=true}else x.lineTo(xx,yy)});x.strokeStyle=s.color;x.lineWidth=2;x.stroke()}
 const current=pad.l+W*Math.min(run.duration_s,video.currentTime||0)/run.duration_s;x.beginPath();x.moveTo(current,pad.t);x.lineTo(current,pad.t+H);x.strokeStyle='#f4fbf8';x.lineWidth=1.3;x.stroke();x.fillStyle='#f4fbf8';x.beginPath();x.arc(current,pad.t+H,3,0,7);x.fill();
 c.onclick=e=>{const rect=c.getBoundingClientRect();let fraction=(e.clientX-rect.left-pad.l)/W;video.currentTime=Math.max(0,Math.min(run.duration_s-.04,fraction*run.duration_s));tick(true)};
}
function drawTrajectory(){const c=$('#trajectory'),{x,w,h}=setupCanvas(c);x.clearRect(0,0,w,h);const pad=20,W=w-40,H=h-40;for(let k=0;k<=4;k++){x.strokeStyle='#30414a';x.lineWidth=1;x.beginPath();x.moveTo(pad+W*k/4,pad);x.lineTo(pad+W*k/4,pad+H);x.moveTo(pad,pad+H*k/4);x.lineTo(pad+W,pad+H*k/4);x.stroke()}const pts=run.timeline.map(r=>r.points[selected]);x.beginPath();let open=false;pts.forEach(p=>{if(!p){open=false;return}const xx=pad+W*p[0]/840,yy=pad+H*p[1]/646;if(!open){x.moveTo(xx,yy);open=true}else x.lineTo(xx,yy)});x.strokeStyle=colors.cyan;x.lineWidth=2;x.stroke();const p=frame().points[selected];if(p){x.beginPath();x.arc(pad+W*p[0]/840,pad+H*p[1]/646,5,0,7);x.fillStyle='#fff';x.fill()}}
function drawCharts(){const tl=run.timeline,j=selected;const col=(fn)=>tl.map(fn);lineChart('speedChart',[{values:col(r=>r.speed_px_s[j]),color:colors.cyan}],{min:0});lineChart('distanceChart',[{values:col(r=>r.reference_distance_px),color:colors.cyan}],{min:0});lineChart('coverageChart',[{values:col(r=>r.coverage),color:colors.cyan}],{min:0,max:7});lineChart('stillChart',[{values:col(r=>r.still_duration_s[j]),color:colors.cyan}],{min:0});lineChart('vibrationChart',[{values:col(r=>r.signals[j].vibration),color:colors.amber}]);lineChart('temperatureChart',[{values:col(r=>r.signals[j].temperature),color:colors.amber}]);lineChart('soundChart',[{values:col(r=>r.signals[j].sound),color:colors.amber}]);lineChart('gapChart',[{values:col(r=>r.signals[j].pose_gap_px),color:colors.amber}],{min:0});lineChart('delayChart',[{values:col(r=>r.signals[j].cycle_delay_s),color:colors.amber}],{min:0});lineChart('scoreChart',[{values:col(r=>r.signals[j].score),color:colors.red}],{min:0,max:100});drawTrajectory()}
function tick(force=false){if(!run)return;const now=performance.now();if(!force&&now-lastDraw<60)return;lastDraw=now;const i=idx(),r=run.timeline[i],p=r.points[selected];el.seek.value=Math.min(video.currentTime,Number(el.seek.max));el.time.textContent=`${fmt(video.currentTime||0)} / ${fmt(run.duration_s)}`;el.big.textContent=fmt(video.currentTime||0);el.frame.textContent=`frame ${String(i).padStart(3,'0')} / ${run.timeline.length-1}`;el.play.textContent=video.paused?'▶':'Ⅱ';$('#visibleBadge').textContent=`${r.coverage} / 7 MỐC`;updateLandmarks(r);$('#selectedName').textContent=run.landmarks[selected];$('#xyValue').textContent=p?`${p[0].toFixed(0)} / ${p[1].toFixed(0)}`:'Bị che khuất';$('#speedValue').textContent=r.speed_px_s[selected]===null?'—':`${r.speed_px_s[selected].toFixed(1)} px/s`;$('#coverageValue').textContent=`${r.coverage} / 7`;$('#distanceValue').textContent=r.reference_distance_px===null?'—':`${r.reference_distance_px.toFixed(1)} px`;drawOverlay(r);drawCharts()}
function playbackLoop(){raf=0;tick();if(!video.paused)raf=requestAnimationFrame(playbackLoop)}
function renderInjections(){const holder=$('#injectionList');holder.innerHTML=run.injections.length?run.injections.map((a,i)=>`<div class="injection-chip">${escapeHtml(faultNames[a.fault])} · ${escapeHtml(run.landmarks[a.landmark].split(' / ')[0])} · ${a.start_s.toFixed(1)}–${(a.start_s+a.duration_s).toFixed(1)}s <button data-remove="${i}" aria-label="Xóa kịch bản">×</button></div>`).join(''):'<span class="subtle">Chưa có lỗi mô phỏng.</span>';holder.querySelectorAll('button').forEach(b=>b.onclick=()=>saveRun(run.injections.filter((_,i)=>i!==Number(b.dataset.remove))))}
function renderIncidents(){const holder=$('#incidentList');$('#incidentCount').textContent=run.incidents.length;holder.innerHTML=run.incidents.length?run.incidents.map(a=>{const fb=run.feedback[a.id];return `<div class="incident ${expanded===a.id?'active':''}"><div class="incident-top"><button data-open="${a.id}">${escapeHtml(a.label)}</button><span>SIM · ${a.start_s.toFixed(1)}s</span></div><div class="incident-meta">${escapeHtml(run.landmarks[a.landmark])} · ${a.start_s.toFixed(1)}–${a.end_s.toFixed(1)} s · ${fb?'ĐÃ XÁC NHẬN':'CHƯA XÁC NHẬN'}</div>${expanded===a.id?`<div class="incident-body"><strong>Giả thuyết:</strong> ${escapeHtml(a.cause)}. Đây là cảnh báo sinh từ kịch bản mô phỏng.<br><strong>Kiểm tra đề xuất:</strong><ul>${a.checks.map(c=>`<li>${escapeHtml(c)}</li>`).join('')}</ul><form class="feedback-form" data-id="${a.id}"><label>Kết luận<select name="correct"><option value="true" ${fb?.correct?'selected':''}>Dự đoán đúng</option><option value="false" ${fb&&!fb.correct?'selected':''}>Dự đoán sai</option></select></label><label>Kỹ thuật viên<input name="technician" required value="${escapeHtml(fb?.technician||'')}" placeholder="Tên người xác nhận"></label><label>Nguyên nhân thực tế<input name="actual_cause" value="${escapeHtml(fb?.actual_cause||'')}" placeholder="Bắt buộc nếu dự đoán sai"></label><label>Việc đã làm<textarea name="action" required placeholder="Kiểm tra, sửa chữa, đo lại...">${escapeHtml(fb?.action||'')}</textarea></label><button class="primary">Lưu xác nhận</button><span class="feedback-state">${fb?`Đã lưu: ${fb.correct?'đúng':'sai'} · ${escapeHtml(fb.created_at)} UTC`:''}</span></form></div>`:''}</div>`}).join(''):'<div class="subtle">Không có kịch bản lỗi. Pose thật vẫn phát theo video.</div>';holder.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const a=run.incidents.find(x=>x.id===b.dataset.open);expanded=expanded===a.id?null:a.id;selected=a.landmark;video.currentTime=a.start_s;renderLandmarks();renderIncidents();tick(true)});holder.querySelectorAll('form').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(f));try{await api(`/api/run/${run.id}/incidents/${f.dataset.id}/feedback`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({correct:data.correct==='true',actual_cause:data.actual_cause,action:data.action,technician:data.technician})});run=await api(`/api/run/${run.id}`);renderIncidents()}catch(err){alert(err.message)}})}
async function saveRun(items){try{const result=await api('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({injections:items})});expanded=null;await load(result.id)}catch(err){alert(err.message)}}
$('#addFault').onclick=()=>saveRun([...run.injections,{fault:$('#faultType').value,landmark:Number($('#faultLandmark').value),start_s:Number($('#faultStart').value),duration_s:Number($('#faultDuration').value),intensity:Number($('#faultIntensity').value)}]);$('#resetFault').onclick=()=>saveRun([{fault:'bearing',landmark:3,start_s:5,duration_s:3,intensity:1},{fault:'backlash',landmark:5,start_s:10,duration_s:3,intensity:1}]);$('#clearFault').onclick=()=>saveRun([]);$('#faultIntensity').oninput=e=>$('#intensityText').textContent=`${Number(e.target.value).toFixed(1)}×`;
el.play.onclick=()=>{if(video.paused){if(video.ended)video.currentTime=0;video.play()}else video.pause();tick(true)};el.seek.oninput=e=>{video.currentTime=Number(e.target.value);tick(true)};$('#speed').onchange=e=>video.playbackRate=Number(e.target.value);video.onplay=()=>{tick(true);if(!raf)raf=requestAnimationFrame(playbackLoop)};video.onpause=()=>tick(true);video.onseeked=()=>tick(true);video.onended=()=>tick(true);window.onresize=()=>tick(true);load().catch(e=>{document.body.insertAdjacentHTML('afterbegin',`<div style="padding:20px;background:#6b2828;color:white">${escapeHtml(e.message)}</div>`)});
